# Generated by Django 5.0.1 on 2024-01-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('weight', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('is_stackable', models.BooleanField(default=False)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('pickup_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
