# Generated by Django 5.0.1 on 2024-01-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='is_hazardous',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='is_stackable',
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_quotation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20),
        ),
    ]
