# Generated by Django 5.0.1 on 2024-01-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0002_remove_shipment_is_hazardous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='drop_off_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_address',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
