# Generated by Django 5.0.1 on 2024-01-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0003_shipment_drop_off_address_shipment_pickup_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='direct_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='drop_off_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
