# Generated by Django 5.0.1 on 2024-01-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0004_shipment_direct_distance_shipment_drop_off_city_and_more'),
        ('users', '0004_remove_shipperindividualuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipper_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.shipperuser'),
            preserve_default=False,
        ),
    ]
