# Generated by Django 5.0.1 on 2024-02-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0005_shipment_shipper_user'),
        ('users', '0005_vehicletype_carrier_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipper_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shipperindividual'),
        ),
    ]
