# Generated by Django 5.0.1 on 2024-03-17 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0007_carrierrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/shipment_qrcodes/'),
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=4)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.carrierrequest')),
            ],
        ),
    ]
