# Generated by Django 5.0.1 on 2024-03-18 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0008_shipment_qrcode_image_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carrierrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'paid')], default='pending', max_length=20),
        ),
    ]
