# Generated by Django 5.0.1 on 2024-03-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0004_carrierplan_status'),
        ('shipper', '0009_paymentdetails_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierrequest',
            name='carrier_plan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrierplan'),
            preserve_default=False,
        ),
    ]
