# Generated by Django 5.0.1 on 2024-04-03 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0012_alter_carrierrequest_quote'),
        ('users', '0006_rename_name_vehicletype_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ship_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.carrierrequest')),
                ('shipper_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shipperuser')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ship_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.carrierrequest')),
                ('shipper_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shipperuser')),
            ],
        ),
    ]
