# Generated by Django 5.0.1 on 2024-04-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0013_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'paid'), ('fulfilled', 'fulfilled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ShipmentRequestTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('picked', 'Picked'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='', max_length=20)),
                ('est_pickup_date', models.DateField()),
                ('est_drop_off_date', models.DateField()),
                ('ship_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.carrierrequest')),
            ],
        ),
    ]
