# Generated by Django 5.0.1 on 2024-04-04 18:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0014_alter_carrierrequest_status_shipmentrequesttracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentrequesttracking',
            name='est_pickup_date',
        ),
        migrations.RemoveField(
            model_name='shipmentrequesttracking',
            name='ship_request',
        ),
        migrations.AddField(
            model_name='shipmentrequesttracking',
            name='est_pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 18, 20, 58, 991806, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentrequesttracking',
            name='shipment',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='shipper.shipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipmentrequesttracking',
            name='est_drop_off_date',
            field=models.DateTimeField(),
        ),
    ]
