# Generated by Django 5.0.1 on 2024-04-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0015_remove_shipmentrequesttracking_est_pickup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentrequesttracking',
            name='est_drop_off_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentrequesttracking',
            name='est_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
