# Generated by Django 5.0.1 on 2024-04-04 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0008_carriercurrentlocation'),
        ('shipper', '0016_alter_shipmentrequesttracking_est_drop_off_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentrequesttracking',
            name='carrier_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrierplan'),
            preserve_default=False,
        ),
    ]
