# Generated by Django 5.0.1 on 2024-02-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierplan',
            name='end_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carrierplan',
            name='start_city',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
