# Generated by Django 5.0.1 on 2024-02-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_carrierplan_end_city_carrierplan_start_city'),
        ('users', '0005_vehicletype_carrier_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrierplan',
            name='user',
        ),
        migrations.AddField(
            model_name='carrierplan',
            name='carrier_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.carrier'),
            preserve_default=False,
        ),
    ]
