# Generated by Django 5.0.1 on 2024-02-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0003_remove_carrierplan_user_carrierplan_carrier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierplan',
            name='status',
            field=models.CharField(blank=True, default='Open', max_length=20),
        ),
    ]
