# Generated by Django 5.0.1 on 2024-03-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0004_carrierplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierplan',
            name='space_available',
            field=models.FloatField(help_text='Space available in van in percentage'),
        ),
    ]
