# Generated by Django 5.0.1 on 2024-04-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0005_alter_carrierplan_space_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierPlanRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_data', models.JSONField()),
                ('carrier_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.carrierplan')),
            ],
        ),
    ]
