# Generated by Django 5.0.1 on 2024-04-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0007_carrierplanroute_path_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierCurrentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('carrier_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.carrierplan')),
            ],
        ),
    ]
